export type Question = {
  id: string;
  day: number;
  prompt: string;
  options: string[];
  correct: string;
  explanation: string;
};
export type Lesson = {
  day: number;
  title: string;
  category: string;
  description: string;
  goals: string[];
  sections: [string, string][];
  example: string;
  task: string;
  solution: string;
  mistakes: string;
  summary: string;
  extension: string;
  quiz: Question[];
};
type Row = [string, string, string, string, string];
function L(
  day: number,
  title: string,
  category: string,
  description: string,
  goals: string[],
  sections: [string, string][],
  example: string,
  task: string,
  solution: string,
  mistakes: string,
  summary: string,
  extension: string,
  rows: Row[],
): Lesson {
  return {
    day,
    title,
    category,
    description,
    goals,
    sections,
    example,
    task,
    solution,
    mistakes,
    summary,
    extension,
    quiz: rows.map((r, i) => ({
      id: `d${day}-q${i + 1}`,
      day,
      prompt: r[0],
      correct: r[1],
      options: r.slice(1, 4),
      explanation: r[4],
    })),
  };
}
export const lessons: Lesson[] = [
  L(
    1,
    "Trading verstehen",
    "Das Fundament",
    "Was Trading ist. Und was es nicht ist.",
    [
      "Trading von Investieren unterscheiden",
      "Unsicherheit und Verlustrisiken erklären",
    ],
    [
      [
        "Eine Entscheidung unter Unsicherheit",
        "Trading bedeutet, Positionen zu eröffnen und zu schließen, um von Preisänderungen zu profitieren. Eine Position ist eine gehaltene Menge eines Instruments. Investieren richtet sich typischerweise längerfristig auf Wertentwicklung und Erträge. Die Grenze ist fließend; beides kann Geld verlieren.",
      ],
      [
        "Preise sind keine Versprechen",
        "Ein Chart zeigt vergangene Preise, keine sichere Zukunft. Brutto bedeutet vor Kosten, netto nach Kosten. Häufiges Handeln kann Kosten vervielfachen. Hier übst du ausschließlich mit erfundenen Preisen und ohne Echtgeld.",
      ],
      [
        "Prozess vor Ergebnis",
        "Ein unüberlegter Versuch kann zufällig gewinnen, ein gut geplanter verlieren. Bewerte, ob die Entscheidung nachvollziehbar war. Das Ziel ist Verständnis, keine bestimmte Handelsstrategie.",
      ],
    ],
    "Kauf 100 €, Verkauf 103 €, eine Einheit, 2 € Gesamtkosten: 3 € brutto, 1 € netto.",
    "Kauf 50 €, Verkauf 48 €, eine Einheit, 1 € Kosten: netto?",
    "−3 € = (48−50)−1.",
    "Gewinne mit Können verwechseln; einen sicheren Tagesgewinn erwarten.",
    "Trading ist unsicher. Bewerte den Prozess getrennt vom Ergebnis.",
    "Vergleicht gute Planung mit Verlust, schlechte Planung mit Gewinn und bewusstes Auslassen. Notiert jeweils die Qualität der Entscheidung.",
    [
      [
        "Das Ziel dieser Academy?",
        "Grundlagen verstehen",
        "Sichere Gewinne",
        "Handelssignale",
        "Lernnachweise prüfen Verständnis und versprechen keinen Gewinn.",
      ],
      [
        "Trading beschreibt …",
        "Handeln auf Preisänderungen",
        "Garantiertes Sparen",
        "Nur Unternehmensbesitz",
        "Die Absicht richtet sich auf Preisänderungen; Verluste sind möglich.",
      ],
      [
        "Netto bedeutet …",
        "nach Kosten",
        "vor Kosten",
        "ohne Verluste",
        "Kosten werden vom Bruttoergebnis abgezogen.",
      ],
      [
        "Kauf 100, Verkauf 104, Kosten 2: netto?",
        "2 €",
        "4 €",
        "6 €",
        "4 € brutto minus 2 € Kosten = 2 €.",
      ],
      [
        "Ein zufälliger Gewinn beweist …",
        "keinen verlässlichen Vorteil",
        "eine sichere Strategie",
        "Risikofreiheit",
        "Ein einzelnes Ergebnis liefert keinen verlässlichen Nachweis.",
      ],
      [
        "Ein historischer Chart zeigt …",
        "vergangene Preise",
        "sichere Zukunft",
        "garantierte Ausführungen",
        "Die dargestellten Preise liegen in der Vergangenheit.",
      ],
      [
        "Investieren hat typischerweise …",
        "einen längeren Horizont",
        "kein Verlustrisiko",
        "nur Tagesgeschäfte",
        "Horizont und Absicht unterscheiden sich häufig, Risiken bleiben.",
      ],
      [
        "Die Academy verwendet …",
        "simulierte Daten",
        "echtes Guthaben",
        "Brokerempfehlungen",
        "Kein Auftrag wird an einen Markt gesendet.",
      ],
    ],
  ),
  L(
    2,
    "Märkte & Instrumente",
    "Das Fundament",
    "Ein Name ist noch kein handelbares Produkt.",
    [
      "Aktie, Index, ETF, CFD und Future unterscheiden",
      "Produktspezifikationen prüfen",
    ],
    [
      [
        "Anteil, Korb und Messgröße",
        "Eine Aktie ist ein Unternehmensanteil. Ein Index fasst die Entwicklung ausgewählter Werte nach Regeln zusammen. Ein ETF ist ein börsengehandelter Fonds, der etwa einen Index abbildet. Der Index selbst ist kein kaufbarer Anteil.",
      ],
      [
        "Verträge statt Besitz",
        "Ein CFD ist ein Differenzvertrag mit einem Anbieter über Preisänderungen. Ein Future ist ein standardisierter Terminkontrakt mit Bedingungen wie Fälligkeit und Kontraktgröße. Eigenschaften hängen vom konkreten Produkt ab.",
      ],
      [
        "Erst spezifizieren, dann rechnen",
        "Dow Jones, US30 und DJI identifizieren allein keinen Kontrakt. Kläre Anbieter, Währung, Punktwert (Geldwert je Preiseinheit und Einheit), Mindestmenge, Stückelung und Kosten. Ein Tick ist die kleinste zulässige Preisänderung.",
      ],
    ],
    "Instrument A hat 1 €/Punkt/Einheit, B hat 5 €/Punkt/Einheit. Zehn Punkte bedeuten je Einheit 10 € oder 50 €.",
    "Tickgröße 0,25 Punkte, Punktwert 4 €/Punkt/Einheit: Tickwert?",
    "1 € je Einheit = 0,25×4.",
    "Einen fremden Punktwert übernehmen; Index und CFD gleichsetzen.",
    "Produktname, Kontrakt und Punktwert getrennt prüfen.",
    "Erstellt zwei fiktive Produktkarten und berechnet dieselbe Preisbewegung für beide.",
    [
      [
        "Eine Aktie ist …",
        "ein Unternehmensanteil",
        "immer ein CFD",
        "ein Indexstand",
        "Aktien verbriefen Anteile, CFDs sind Verträge.",
      ],
      [
        "Ein Index ist …",
        "eine berechnete Messgröße",
        "ein Konto",
        "immer ein Future",
        "Handelbare Produkte können sich auf den Index beziehen.",
      ],
      [
        "Ein ETF ist …",
        "ein börsengehandelter Fonds",
        "ein Gewinnversprechen",
        "nur ein Indexstand",
        "ETF-Anteile sind handelbar und können an Wert verlieren.",
      ],
      [
        "Ein CFD ist …",
        "ein Differenzvertrag",
        "Unternehmenseigentum",
        "ein Sparkonto",
        "Der Vertrag und die Anbieterbedingungen bestimmen seine Eigenschaften.",
      ],
      [
        "Ein Future hat …",
        "festgelegte Kontraktbedingungen",
        "keine Spezifikation",
        "immer 1 € Punktwert",
        "Fälligkeit und Tickwert sind produktspezifisch.",
      ],
      [
        "Reicht US30 zur Risikorechnung?",
        "Nein, der Kontrakt fehlt",
        "Ja, immer 1 €/Punkt",
        "Ja, immer 5 €/Punkt",
        "Das Kürzel identifiziert keinen universellen Punktwert.",
      ],
      [
        "0,5 Punkte × 2 €/Punkt: Tickwert?",
        "1 €",
        "4 €",
        "0,25 €",
        "Tickgröße mal Punktwert ergibt den Tickwert je Einheit.",
      ],
      [
        "Vor der Simulation klären …",
        "Punktwert, Stückelung, Kosten",
        "nur den Namen",
        "nur die Chartfarbe",
        "Ohne Einheiten und Kosten bleibt die Rechnung unvollständig.",
      ],
    ],
  ),
  L(
    3,
    "Kerzen lesen",
    "Charts verstehen",
    "Vier Preise erzählen eine kleine Geschichte.",
    ["Chartachsen lesen", "OHLC, Körper und Dochte erklären"],
    [
      [
        "Zwei Achsen",
        "Waagrecht steht die Zeit, senkrecht der Preis. Unsere Preisachsen sind linear: gleiche Abstände bedeuten gleiche Preisänderungen. Die Bildschirmgröße einer Bewegung ist noch kein Geldrisiko.",
      ],
      [
        "Vier Werte",
        "OHLC heißt Open (Eröffnung), High (Hoch), Low (Tief), Close (Schluss). Der Kerzenkörper verbindet Eröffnung und Schluss. Dochte reichen bis Hoch und Tief. Grün mit + heißt Schluss über Eröffnung, Rot mit − darunter.",
      ],
      [
        "Grenzen der Darstellung",
        "OHLC verrät nicht, ob Hoch oder Tief zuerst erreicht wurde. Offene Kerzen können sich noch verändern. Ein Doji hat nahezu gleiche Eröffnung und Schluss und garantiert keine Umkehr.",
      ],
    ],
    "O100, H108, L97, C105: Körper 100–105, oberer Docht 105–108, unterer Docht 97–100.",
    "O102, H106, L98, C99: Körpergröße und Spanne?",
    "3 Punkte Körper, 8 Punkte Spanne. Fallende Kerze (−).",
    "Körperoberkante für das Hoch halten; OHLC mit einem genauen Kursweg verwechseln.",
    "Vier Werte verdichten den Verlauf, sie erzählen nicht jeden Zwischenschritt.",
    "Wählt fünf Kerzen im Chart und notiert Körper, Dochte und Spanne.",
    [
      [
        "O steht für …",
        "Eröffnung",
        "Hoch",
        "Volumen",
        "Open ist der erste Preis des Intervalls.",
      ],
      [
        "H steht für …",
        "höchsten Preis",
        "Schluss",
        "Tief",
        "High ist der höchste Preis des Intervalls.",
      ],
      [
        "Der Körper verbindet …",
        "Eröffnung und Schluss",
        "Hoch und Tief",
        "zwei Hochs",
        "Die Dochte ergänzen die Extremwerte.",
      ],
      [
        "O100, C104 bedeutet …",
        "steigende Kerze (+)",
        "fallende Kerze (−)",
        "sicheren nächsten Gewinn",
        "Der Schluss liegt über der Eröffnung.",
      ],
      [
        "H110, L102: Spanne?",
        "8 Punkte",
        "4 Punkte",
        "212 Punkte",
        "Hoch minus Tief ergibt 8.",
      ],
      [
        "O106, C101: Körpergröße?",
        "5 Punkte",
        "−5 Punkte",
        "107 Punkte",
        "Die Größe ist der Betrag der Differenz.",
      ],
      [
        "OHLC zeigt die Reihenfolge von Hoch und Tief …",
        "nicht",
        "immer Hoch zuerst",
        "immer Tief zuerst",
        "Mehrere Kurswege ergeben dieselbe Kerze.",
      ],
      [
        "Waagrechte Chartachse?",
        "Zeit",
        "Geldrisiko",
        "Positionsgröße",
        "Die senkrechte Achse zeigt den Preis.",
      ],
    ],
  ),
  L(
    4,
    "Zeitrahmen verstehen",
    "Charts verstehen",
    "Derselbe Verlauf, verschiedene Perspektiven.",
    ["Kerzen zusammenfassen", "Zeitzonen mit Datum berücksichtigen"],
    [
      [
        "Ein Intervall bündelt Daten",
        "Ein Zeitrahmen bestimmt die Dauer einer Kerze. Fünf vollständige 1-Minuten-Kerzen ergeben eine 5-Minuten-Kerze: erste Eröffnung, höchstes Hoch, tiefstes Tief, letzter Schluss.",
      ],
      [
        "Details und Überblick",
        "Kleine Zeitrahmen zeigen mehr kurzfristige Details. Größere verstecken den Weg dazwischen. Ein lokaler Anstieg kann Teil eines größeren Rückgangs sein. Keine Skala liefert allein eine Prognose.",
      ],
      [
        "Uhrzeiten im Kontext",
        "Handelszeiten hängen von Börse, Produkt, Sitzung und Feiertagen ab. Verwende Europe/Vienna und beispielsweise America/New_York mit konkretem Datum. Unterschiedliche Sommerzeitwechsel ändern zeitweise die Differenz; eine feste ganzjährige Umrechnung wäre falsch.",
      ],
    ],
    "(O100,H104,L99,C103) und (O103,H106,L101,C102) ergeben O100,H106,L99,C102.",
    "Tiefs zweier Kerzen: 49 und 48. Gemeinsames Tief?",
    "48, das Minimum.",
    "Schlusskurse mitteln statt letzten Schluss nehmen; Uhrzeiten ohne Datum umrechnen.",
    "Größere Intervalle verdichten dieselben Daten und verlieren Details.",
    "Wechselt im Chart zwischen 1 und 5 Minuten und vergleicht die Extremwerte.",
    [
      [
        "Fünf 1-Minuten-Kerzen ergeben …",
        "eine 5-Minuten-Kerze",
        "fünf Stunden",
        "fünf Tage",
        "Die Intervalle werden zusammengefasst.",
      ],
      [
        "Aggregierte Eröffnung?",
        "Erste Eröffnung",
        "Mittelwert",
        "Letzter Schluss",
        "Der erste Preis des gesamten Intervalls zählt.",
      ],
      [
        "Aggregierter Schluss?",
        "Letzter Schluss",
        "Höchstes Hoch",
        "Erste Eröffnung",
        "Der letzte Preis des gesamten Intervalls zählt.",
      ],
      [
        "Hochs 105 und 108: gemeinsames Hoch?",
        "108",
        "106,5",
        "105",
        "Es zählt das Maximum.",
      ],
      [
        "Tiefs 97 und 99: gemeinsames Tief?",
        "97",
        "99",
        "98",
        "Es zählt das Minimum.",
      ],
      [
        "Ein größerer Zeitrahmen …",
        "versteckt Details",
        "erzeugt sichere neue Daten",
        "garantiert Trends",
        "Der innere Weg ist nicht vollständig sichtbar.",
      ],
      [
        "Wien und New York haben …",
        "datumsabhängige Zeitdifferenzen",
        "immer gleiche Differenz",
        "dieselbe Ortszeit",
        "Sommerzeitwechsel können an unterschiedlichen Tagen liegen.",
      ],
      [
        "Ein kleiner Aufwärtstrend kann …",
        "Teil eines größeren Rückgangs sein",
        "nur global steigen",
        "keine Rückgänge enthalten",
        "Struktur hängt vom Ausschnitt ab.",
      ],
    ],
  ),
  L(
    5,
    "Marktstruktur erkennen",
    "Charts verstehen",
    "Hochs und Tiefs statt Bauchgefühl.",
    ["Bestätigte Swings markieren", "Trends und Seitwärtsphasen unterscheiden"],
    [
      [
        "Eine feste Swing-Regel",
        "Ein Swing-Hoch liegt hier strikt höher als die Hochs der zwei linken und zwei rechten Kerzen. Ein Swing-Tief entsprechend niedriger. Erst nach Schluss der zweiten rechten Kerze ist es bestätigt. Gleiche Nachbarhochs erfüllen diese Regel nicht.",
      ],
      [
        "Struktur vergleichen",
        "HH heißt höheres Hoch, HL höheres Tief, LH tieferes Hoch und LL tieferes Tief. HH und HL beschreiben Aufwärtsstruktur, LH und LL Abwärtsstruktur. Überlappende Hochs und Tiefs sprechen eher für eine Seitwärtsphase.",
      ],
      [
        "Nur sichtbare Informationen",
        "Am rechten Rand fehlen oft Bestätigungskerzen. Nutze keine Zukunftsdaten. Ein Strukturbruch kann eine Veränderung anzeigen, garantiert aber keinen neuen Trend. Die Swing-Regel muss vor der Auswertung feststehen.",
      ],
    ],
    "Hochs 104→110 und Tiefs 98→102: HH und HL im betrachteten Ausschnitt.",
    "Mögliches Hoch an Kerze 8, sichtbar bis Kerze 9: bestätigt?",
    "Nein. Auch Kerze 10 muss geschlossen sein und ein niedrigeres Hoch haben.",
    "Zukünftige Kerzen benutzen; jeden Zacken als Swing zählen.",
    "Struktur ist eine Beschreibung nach einer festen Regel, keine Garantie.",
    "Vergleicht auf Papier Regeln mit einer und zwei Bestätigungskerzen.",
    [
      [
        "HH bedeutet …",
        "höheres Hoch",
        "höheres Risiko",
        "tieferes Tief",
        "Higher High vergleicht bestätigte Hochpunkte.",
      ],
      [
        "HL bedeutet …",
        "höheres Tief",
        "tieferes Hoch",
        "gleiches Hoch",
        "Higher Low vergleicht bestätigte Tiefpunkte.",
      ],
      [
        "HH und HL beschreiben …",
        "Aufwärtsstruktur",
        "Abwärtsstruktur",
        "sichere Gewinne",
        "Die Struktur beschreibt nur den betrachteten Verlauf.",
      ],
      [
        "LH und LL beschreiben …",
        "Abwärtsstruktur",
        "Aufwärtsstruktur",
        "immer Seitwärtsbewegung",
        "Hochs und Tiefs liegen niedriger.",
      ],
      [
        "Unsere Bestätigung braucht …",
        "zwei geschlossene rechte Kerzen",
        "keine rechte Kerze",
        "nur eine linke Kerze",
        "Auch zwei linke Kerzen dienen als Vergleich.",
      ],
      [
        "Am Rand fehlen rechte Kerzen: Swing …",
        "noch unbestätigt",
        "sicher bestätigt",
        "automatisch falsch",
        "Fehlende Daten dürfen nicht vorweggenommen werden.",
      ],
      [
        "Gleiche Nachbarhochs sind hier …",
        "kein strikter Swing",
        "immer HH",
        "sichere Umkehr",
        "Die Regel verlangt strikt höhere Werte.",
      ],
      [
        "Hochs 110→108, Tiefs 101→98?",
        "Abwärtsstruktur",
        "Aufwärtsstruktur",
        "kein Verlauf",
        "Beide Folgen sinken: LH und LL.",
      ],
    ],
  ),
  L(
    6,
    "Unterstützung & Widerstand",
    "Charts verstehen",
    "Bereiche erkennen, keine magischen Linien.",
    ["Reaktionsbereiche zeichnen", "Toleranzen begründen"],
    [
      [
        "Frühere Reaktionen",
        "Unterstützung bezeichnet einen Bereich, in dem fallende Preise zuvor auf Nachfrage trafen. Widerstand einen Bereich, in dem steigende Preise auf Verkaufsinteresse trafen. Beides sind Beobachtungen, keine unüberwindbaren Barrieren.",
      ],
      [
        "Bereiche statt Scheingenauigkeit",
        "Tiefs bei 99, 100 und 101 lassen sich zu 99–101 bündeln. Körper und Dochte können unterschiedliche plausible Grenzen liefern. Wenige gut begründete Zonen sind besser nachvollziehbar als viele präzise Linien.",
      ],
      [
        "Offene Bewertungsregel",
        "Unsere Übung akzeptiert Grenzen innerhalb von ±1 Punkt um den beobachteten Reaktionsbereich und Breiten von 1–5 Punkten. Das ist eine didaktische Toleranz, kein Marktgesetz. Markierungen bleiben Hypothesen.",
      ],
    ],
    "Reaktionen um 100 und 112: mögliche Unterstützung 99–101, Widerstand 111–113.",
    "Sind 98–102 und 99–101 für Tiefs 99,100,101 beide begründbar?",
    "Ja, bei offengelegter Toleranz. Der breitere Bereich ist weniger präzise.",
    "Zu viele Linien; Bereiche als sichere Einstiege ansehen.",
    "Eine Zone braucht sichtbare Reaktionen und nachvollziehbare Grenzen.",
    "Markiert unabhängig Zonen und vergleicht eure Begründungen.",
    [
      [
        "Unterstützung ist …",
        "ein Reaktionsbereich",
        "garantierte Untergrenze",
        "immer ein Cent",
        "Ein Durchbruch bleibt möglich.",
      ],
      [
        "Widerstand beschreibt …",
        "frühere Reaktionen bei Anstiegen",
        "garantierte Verkäufe",
        "ein festes Kursziel",
        "Vergangenheit verspricht keine zukünftige Reaktion.",
      ],
      [
        "Tiefs 99,100,101 passen zu …",
        "99–101",
        "exakt 100,0000",
        "140–150",
        "Die Zone bündelt nahe Reaktionen.",
      ],
      [
        "Warum Toleranzen zeigen?",
        "Nachvollziehbare Bewertung",
        "Jede Linie ist richtig",
        "Verluste ausschließen",
        "Die Übungsregel wird überprüfbar.",
      ],
      [
        "Zwei plausible Bereiche …",
        "können beide begründbar sein",
        "sind unmöglich",
        "beweisen einen Fehler",
        "Interpretierbare Charts haben nicht immer eine einzige richtige Linie.",
      ],
      [
        "Zu viele Markierungen …",
        "verstellen den Blick",
        "garantieren Treffer",
        "ersetzen Risikorechnung",
        "Begründung zählt mehr als Anzahl.",
      ],
      [
        "Ein Durchbruch ist …",
        "möglich",
        "ausgeschlossen",
        "immer Datenfehler",
        "Frühere Nachfrage garantiert keine zukünftige.",
      ],
      [
        "±1 Punkt Toleranz ist …",
        "eine Übungsvereinbarung",
        "ein Börsengesetz",
        "eine Gebühr",
        "Andere Daten können andere Toleranzen benötigen.",
      ],
    ],
  ),
  L(
    7,
    "Dein erster Check-in",
    "Wiederholen & verbinden",
    "Zusammenhänge verstehen, Lücken entdecken.",
    ["Produkt und Chart verbinden", "Fehler gezielt wiederholen"],
    [
      [
        "Die richtige Reihenfolge",
        "Kläre erst das Produkt und seine Einheit, dann Achsen und Zeitrahmen. Beschreibe danach Kerzen, bestätigte Swings und Bereiche. Eine Preisbewegung in Punkten ist noch kein Geldgewinn.",
      ],
      [
        "Aktiv abrufen",
        "Erkläre deinem Lernpartner eine Kerze ohne nachzusehen. Begründe einen Bereich. Notiere konkrete Unsicherheiten statt pauschaler Urteile über dich. Ein Pausentag löscht keinen Fortschritt.",
      ],
      [
        "Zwischentest",
        "Unter Tests warten 20 Fragen aus Tagen 1–7. Ab 80 % gilt der Test als bestanden. Falsche Antworten werden nach ungefähr 1, 3 und 7 Tagen wiederholt. Bloßes Lesen ist kein bestandener Test.",
      ],
    ],
    "4 Punkte × 2 €/Punkt × 1 Einheit = 8 € brutto. Im Chart bleiben es 4 Punkte.",
    "16 von 20 Antworten richtig: Prozent?",
    "80 %. Einzelne Fehler bleiben trotzdem in der Wiederholung.",
    "Antwortpositionen merken statt Begriffe erklären; Note mit Marktreife verwechseln.",
    "Verbinde Grundlagen und prüfe sie aktiv, in deinem Tempo.",
    "Stellt einander eigene Zahlenaufgaben zu den zwei schwächsten Themen.",
    [
      [
        "16 von 20 sind …",
        "80 %",
        "60 %",
        "90 %",
        "16 geteilt durch 20 = 0,8; mal 100 ergibt 80 %.",
      ],
      [
        "Lesen beweist …",
        "noch kein Verständnis",
        "automatisch Beherrschung",
        "Profitabilität",
        "Aufgaben prüfen aktives Abrufen.",
      ],
      [
        "4 Punkte × 2 €/Punkt × 1 Einheit?",
        "8 € brutto",
        "4 € netto",
        "2 € brutto",
        "Für netto fehlen noch Kosten.",
      ],
      [
        "Vor dem Chart prüfst du …",
        "Produktspezifikation",
        "Wunschgewinn",
        "nur die Farbe",
        "Die Einheit ist Grundlage der Geldrechnung.",
      ],
      [
        "Ein Fehler hilft mit …",
        "Begründung und Übungsschritt",
        "nur roter Farbe",
        "einer Strafe",
        "Eine konkrete Korrektur macht Wiederholung wirksam.",
      ],
      [
        "Wiederholung ungefähr nach …",
        "1, 3, 7 Tagen",
        "1, 3, 7 Minuten",
        "einem Jahr",
        "Die Intervalle verteilen aktives Abrufen.",
      ],
      [
        "Ein Pausentag ist …",
        "erlaubt",
        "ein Reset",
        "Echtgeldpflicht",
        "Lernen soll ohne Bestrafung möglich sein.",
      ],
      [
        "Ein Zwischentest ist …",
        "ein Lernnachweis",
        "Handelsfreigabe",
        "Gewinnversprechen",
        "Er prüft die behandelten Grundlagen.",
      ],
    ],
  ),
  L(
    8,
    "Was ein Preis wirklich bedeutet",
    "Marktmechanik",
    "Spread, Liquidität und Bewegung verstehen.",
    ["Bid und Ask unterscheiden", "Volumenquellen und Slippage erklären"],
    [
      [
        "Zwei Seiten",
        "Bid ist der Preis der Käuferseite, zu dem du typischerweise verkaufen kannst. Ask ist der Preis der Verkäuferseite, zu dem du kaufen kannst. Spread = Ask minus Bid. Quotes können sich bis zur Ausführung ändern.",
      ],
      [
        "Handelbarkeit und Aktivität",
        "Liquidität beschreibt die Handelbarkeit von Mengen ohne starke Preiswirkung. Volumen ist die gehandelte Menge einer Periode. Datenquellen zeigen Börsenvolumen, Teilmärkte oder Tickvolumen, also Preisaktualisierungen. Diese Größen sind nicht gleichbedeutend.",
      ],
      [
        "Bewegung und Abweichung",
        "Volatilität beschreibt die Stärke von Schwankungen. Slippage ist die günstige oder ungünstige Abweichung zwischen erwartetem und tatsächlichem Ausführungspreis. Wenig Liquidität und Preissprünge können sie vergrößern.",
      ],
    ],
    "Bid 100, Ask 100,4: Spread 0,4 Punkte. Sofortiger Kauf/Verkauf verliert bei einer Einheit und 1 €/Punkt 0,40 € vor weiteren Gebühren.",
    "Kauf erwartet 101, tatsächlich 101,6. Zwei Einheiten, 1 €/Punkt: Abweichung?",
    "1,20 € ungünstig = 0,6×2×1.",
    "Tickvolumen als Gesamtmarktvolumen lesen; bereits enthaltenen Spread doppelt abziehen.",
    "Angezeigte Preise garantieren keine Ausführung jeder Menge.",
    "Berechnet Kauf/Verkauf für drei Spreads und trennt enthaltene von zusätzlichen Kosten.",
    [
      [
        "Ask ist typischerweise zum …",
        "Kaufen",
        "Verkaufen",
        "Gewinnen",
        "Du kaufst von der Verkäuferseite.",
      ],
      [
        "Bid ist typischerweise zum …",
        "Verkaufen",
        "Kaufen",
        "Stop garantieren",
        "Du verkaufst an die Käuferseite.",
      ],
      [
        "Bid 50, Ask 50,3: Spread?",
        "0,3 Punkte",
        "100,3 Punkte",
        "3 Punkte",
        "50,3 minus 50 = 0,3 Punkte. Nicht addieren und die Dezimalstelle beachten.",
      ],
      [
        "Liquidität beschreibt …",
        "Handelbarkeit von Mengen",
        "sichere Richtung",
        "Tagesgewinn",
        "Gegenorders beeinflussen Ausführung und Preiswirkung.",
      ],
      [
        "Tickvolumen zählt …",
        "Preisaktualisierungen",
        "alle Kontrakte weltweit",
        "nur Gewinne",
        "Die Quelle bestimmt die Bedeutung von Volumen.",
      ],
      [
        "Volatilität ist …",
        "Schwankungsstärke",
        "eine Gebühr",
        "ein Ordertyp",
        "Stärke sagt allein nichts über Richtung.",
      ],
      [
        "Slippage kann …",
        "günstig oder ungünstig sein",
        "nur Gewinn bedeuten",
        "nie auftreten",
        "Tatsächliche Preise können in beide Richtungen abweichen.",
      ],
      [
        "Spread schon in Ausführungspreisen enthalten?",
        "Nicht erneut abziehen",
        "Doppelt abziehen",
        "Alle Gebühren ignorieren",
        "Sonst zählen dieselben Kosten zweimal.",
      ],
    ],
  ),
  L(
    9,
    "Orders & Ausführung",
    "Marktmechanik",
    "Den Auftrag vor der Simulation verstehen.",
    [
      "Ordertypen passend auswählen",
      "Ausführungs- und Preisrisiko unterscheiden",
    ],
    [
      [
        "Die Richtung",
        "Long profitiert vor Kosten von steigenden, Short von fallenden Preisen. Bei ungedeckten Aktien-Shorts sind Verluste theoretisch unbegrenzt, weil Preise keine feste Obergrenze haben. Produktbedingungen unterscheiden sich.",
      ],
      [
        "Auftrag und Grenze",
        "Market fordert Ausführung zum verfügbaren Preis ohne feste Preisgarantie. Limit setzt eine Preisgrenze und kann unausgeführt bleiben. Stop wird nach Auslösung zur Market-Order. Stop-Limit wird zur Limit-Order und kann einen Ausstieg verpassen.",
      ],
      [
        "Ausstiege planen",
        "Stop-Loss ist ein geplanter Verlustausstieg, Take-Profit ein geplanter Gewinnausstieg. Der hinterlegte Ordertyp zählt. Kurslücken können Stops überspringen. Anbieter und Handelsplatz bestimmen Auslösebedingungen und verfügbare Auftragstypen.",
      ],
    ],
    "Long 100, Verkaufsstop 95, nächster handelbarer Preis 92: Verlust kann 8 statt 5 Punkte sein.",
    "Ask 100, du willst maximal 98 zahlen: welcher Auftrag?",
    "Kauf-Limit 98; keine Ausführungsgarantie.",
    "Stop-Preis als garantierten Verlustdeckel lesen.",
    "Preisgrenze und Ausführungssicherheit sind verschiedene Eigenschaften.",
    "Vergleicht eine Kurslücke auf 92 bei Stop 95 und Stop-Limit 95/94.",
    [
      [
        "Long profitiert vor Kosten von …",
        "steigenden Preisen",
        "fallenden Preisen",
        "jedem Preis",
        "Die Positionsrichtung ist aufwärts.",
      ],
      [
        "Short profitiert vor Kosten von …",
        "fallenden Preisen",
        "steigenden Preisen",
        "nur Seitwärtskursen",
        "Die Positionsrichtung ist abwärts.",
      ],
      [
        "Sofort zum verfügbaren Preis?",
        "Market",
        "Limit",
        "Garantiertes Stop-Limit",
        "Market setzt keine feste Preisgrenze.",
      ],
      [
        "Maximal 98 beim Kauf?",
        "Kauf-Limit 98",
        "Market",
        "Verkaufsstop 98",
        "Das Kauflimit begrenzt den Preis nach oben.",
      ],
      [
        "Stop wird bei Auslösung …",
        "Market-Order",
        "garantiert gefüllt",
        "gelöscht",
        "Der Ausführungspreis kann abweichen.",
      ],
      [
        "Stop-Limit kann …",
        "unausgeführt bleiben",
        "Kurslücken verhindern",
        "immer zum Stop schließen",
        "Die Preisgrenze kann eine Ausführung verhindern.",
      ],
      [
        "Einstieg 100, Stop 95, Ausstieg 92, 1 €/Punkt: Verlust?",
        "8 € vor Kosten",
        "5 € garantiert",
        "3 €",
        "Der tatsächliche Ausstieg bestimmt das Ergebnis.",
      ],
      [
        "Take-Profit ist …",
        "geplanter Gewinnausstieg",
        "sichere Gewinnzusage",
        "Punktwert",
        "Die Ausführung hängt vom Auftrag und Markt ab.",
      ],
    ],
  ),
  L(
    10,
    "Risiko, Hebel & Margin",
    "Risiko verstehen",
    "Ähnliche Zahlen, verschiedene Aufgaben.",
    ["Kapital, Menge und Wert trennen", "Margin nicht mit Risiko verwechseln"],
    [
      [
        "Vier verschiedene Größen",
        "Kontogröße ist verfügbares Kapital. Positionsgröße ist die Menge. Positionswert ist der wirtschaftliche Gegenwert. Geplantes Geldrisiko im linearen Modell: Stop-Abstand × Geldwert je Preiseinheit × Menge, plus modellierte Kosten.",
      ],
      [
        "Hebel verstärkt die Wirkung",
        "Hebel ist Positionswert geteilt durch betrachtetes Eigenkapital. 5.000 € Position bei 1.000 € Kapital entspricht 5:1. Zwei Prozent Bewegung sind 100 €, also zehn Prozent des Kapitals vor Kosten.",
      ],
      [
        "Margin ist Sicherheit",
        "Margin ist eine hinterlegte Sicherheitsleistung, kein maximaler Verlust. Bei unzureichender Deckung können Nachforderungen oder Schließungen folgen. Bedingungen und Schutzregeln hängen von Produkt und Rechtsraum ab.",
      ],
    ],
    "10 Einheiten × 3 Punkte Stop × 2 €/Punkt/Einheit = 60 € geplantes Risiko vor Kosten.",
    "2.000 € Kapital und 10.000 € Position: Hebel?",
    "5:1.",
    "Geringe Margin mit geringem Risiko verwechseln; alle verfügbare Margin ausnutzen.",
    "Menge bestimmt Preisempfindlichkeit; Margin ist kein Verlustdeckel.",
    "Ändert bei gleicher Menge nur die Margin und erklärt, warum das Preisrisiko unverändert bleibt.",
    [
      [
        "Margin ist …",
        "Sicherheitsleistung",
        "sicherer Verlustdeckel",
        "Gewinn",
        "Sie sichert Verpflichtungen und begrenzt nicht den Verlust.",
      ],
      [
        "10.000/2.000 ergibt …",
        "Hebel 5:1",
        "Hebel 2:1",
        "Hebel 10:1",
        "Positionswert geteilt durch Kapital = 5.",
      ],
      [
        "1 % von 10.000 €?",
        "100 €",
        "10 €",
        "1.000 €",
        "Die Bewegung bezieht sich auf den Positionswert.",
      ],
      [
        "100 € Verlust bei 2.000 € Kapital?",
        "5 %",
        "1 %",
        "20 %",
        "100 / 2.000 = 0,05; das entspricht 5 % des Kapitals.",
      ],
      [
        "3 Punkte × 2 €/Punkt × 10 Einheiten?",
        "60 € vor Kosten",
        "15 €",
        "6 €",
        "Alle drei Faktoren werden multipliziert.",
      ],
      [
        "Doppelte Menge bei gleichem Stop?",
        "Doppeltes Preisrisiko",
        "Halbes Risiko",
        "Gleiches Risiko",
        "Das lineare Risiko ist proportional zur Menge.",
      ],
      [
        "Weniger Margin bei gleicher Position …",
        "senkt nicht das Preisrisiko",
        "halbiert Verluste",
        "garantiert den Stop",
        "Dieselbe Menge reagiert gleich auf Preisänderungen.",
      ],
      [
        "Eine Kurslücke kann …",
        "geplantes Risiko überschreiten",
        "nie Stops überspringen",
        "nur Gewinn ändern",
        "Stop-Ausführungspreise sind nicht garantiert.",
      ],
    ],
  ),
  L(
    11,
    "Positionsgröße berechnen",
    "Risiko verstehen",
    "Erst das Budget, dann die Menge.",
    ["Kosten und Stückelung einrechnen", "Drawdown verstehen"],
    [
      [
        "Die Rechnung",
        "Risiko vor Kosten = Stop-Abstand in Punkten × €/Punkt/Einheit × Einheiten. Bei Fixkosten F und Kosten k je Einheit: maximale Menge = (Budget−F)/(Abstand×Punktwert+k). Runde immer auf die erlaubte Stückelung ab.",
      ],
      [
        "Wenn nichts passt",
        "Ist die Mindestmenge zu teuer, ist keine Position innerhalb dieses Budgets möglich. Null beim Stop-Abstand, negative und fehlende Eingaben sind ungültig. Unsere kleinen Budgets sind frei gewählte Übungsgrenzen, keine universell richtigen Risikoprozente.",
      ],
      [
        "Drawdown und Serien",
        "Drawdown ist der Rückgang vom bisherigen Kapitalhoch. 1.000 auf 800 € sind 20 %. Zurück auf 1.000 benötigt von 800 aus 25 % Zuwachs. Verlustserien bleiben auch bei positivem Erwartungswert möglich.",
      ],
    ],
    "Budget 50 €, Stop 8, Punktwert 2 €, Fix 2 €, je Einheit 1 €, Schritt 1: 48/17=2,82 → 2 Einheiten. Risiko 32 € + Kosten 4 € = 36 €.",
    "Budget 30 €, Stop 5, Punktwert 2 €, Fix 2 €, Kosten je Einheit 1 €, Schritt 1: Menge?",
    "2 Einheiten. Geplantes Risiko inklusive Kosten: 24 €.",
    "Aufrunden; fixe Kosten je Einheit multiplizieren; Stop-Risiko als Garantie lesen.",
    "Abrunden und zurückrechnen. Keine passende Menge heißt keine Position.",
    "Rechnet drei Budgets von Hand und kontrolliert sie im Rechner.",
    [
      [
        "2,82 Einheiten, Schritt 1: zulässig?",
        "2",
        "3",
        "2,82",
        "Die Stückelung wird abgerundet.",
      ],
      [
        "Budget 30, Fix 2, Risiko inkl. variabler Kosten 11 je Einheit?",
        "2 Einheiten",
        "3 Einheiten",
        "28 Einheiten",
        "Nach Fixkosten bleiben 28 €. 28/11 = 2,54, auf ganze Einheiten abgerundet 2.",
      ],
      [
        "Stop-Abstand null ist …",
        "ungültig",
        "risikofrei",
        "unbegrenzte Menge",
        "Die Formel verlangt einen positiven Abstand.",
      ],
      [
        "Mindestmenge passt nicht ins Budget?",
        "Keine Position möglich",
        "Trotzdem handeln",
        "Aufrunden",
        "Rundung darf das Budget nicht überschreiten.",
      ],
      [
        "1.000 € Hoch, 800 € Tief: Drawdown?",
        "20 %",
        "25 %",
        "80 %",
        "Der Rückgang beträgt 200 €, geteilt durch das Kapitalhoch 1.000 € ergibt 20 %.",
      ],
      [
        "800 zurück auf 1.000 braucht …",
        "25 %",
        "20 %",
        "10 %",
        "Der nötige Zuwachs ist 200 €, bezogen auf das verbliebene Kapital 800 € sind das 25 %.",
      ],
      [
        "Fix 2 € + 1 € je Einheit bei Menge 3?",
        "5 €",
        "3 €",
        "9 €",
        "Die Fixkosten fallen einmal an: 2 € + 1 € × 3 Einheiten = 5 €.",
      ],
      [
        "Verlustserien sind …",
        "auch bei positivem Erwartungswert möglich",
        "immer Betrugsbeweis",
        "Grund zum Verdoppeln",
        "Ein Durchschnitt garantiert keine Reihenfolge.",
      ],
    ],
  ),
  L(
    12,
    "CRV & Erwartungswert",
    "Risiko verstehen",
    "Ein gutes Verhältnis ist noch kein Vorteil.",
    ["Brutto und netto trennen", "Stichproben kritisch einordnen"],
    [
      [
        "Chance und Risiko",
        "CRV (Chance-Risiko-Verhältnis) ist geplanter Gewinn geteilt durch geplanten Verlust. 100 € Ziel bei 50 € Risiko sind 2:1 vor Kosten. R ist eine Ergebniseinheit: Hier entspricht 1 R dem vorher festgelegten Geldrisiko.",
      ],
      [
        "Häufigkeit zählt",
        "Erwartungswert = Trefferquote × Durchschnittsgewinn − Verlustquote × Durchschnittsverlust. Bei Bruttowerten ziehst du die durchschnittlichen Kosten pro Versuch einmal ab. Bei Nettowerten nicht erneut.",
      ],
      [
        "Unsicherheit bleibt",
        "40 % Treffer, 100 € Gewinn, 50 € Verlust und 5 € Kosten ergeben 5 € erwartetes Netto pro Versuch. Kleine Stichproben schwanken stark. Mehr unabhängige Fälle und verschiedene Marktphasen verbessern die Schätzung, garantieren aber nichts.",
      ],
    ],
    "20 % Treffer bei 150 € Gewinn und 50 € Verlust: trotz CRV 3:1 ist der Brutto-Erwartungswert 30−40=−10 €.",
    "50 % Treffer, 80 € Gewinn, 40 € Verlust, 4 € Kosten: netto E?",
    "16 € = 40−20−4.",
    "Hohes CRV als Vorteil beweisen wollen; Kosten doppelt zählen.",
    "CRV, Trefferquote, Kosten und Unsicherheit gehören zusammen.",
    "Verändert nur die Trefferquote im Rechner und sucht die rechnerische Gewinnschwelle.",
    [
      [
        "100 € Ziel / 50 € Risiko?",
        "CRV 2:1",
        "CRV 1:2",
        "CRV 50:1",
        "Gewinnchance geteilt durch geplantes Risiko.",
      ],
      [
        "CRV 3:1 garantiert …",
        "keinen Vorteil",
        "immer Gewinn",
        "75 % Treffer",
        "Trefferquote und Kosten sind ebenfalls entscheidend.",
      ],
      [
        "0,4×100 − 0,6×50 − 5?",
        "5 €",
        "15 €",
        "35 €",
        "Gewichteter Gewinn 40 € minus gewichteter Verlust 30 € minus Kosten 5 € ergibt 5 €.",
      ],
      [
        "20 % Treffer, Gewinn 150, Verlust 50: brutto E?",
        "−10 €",
        "10 €",
        "30 €",
        "20 % von 150 € ergeben 30 €, 80 % von 50 € ergeben 40 €: 30−40 = −10 €.",
      ],
      [
        "Bereits netto erfasste Ergebnisse …",
        "nicht erneut um Kosten mindern",
        "doppelt mindern",
        "brauchen keine Verlustquote",
        "Doppelte Kosten verfälschen das Ergebnis.",
      ],
      [
        "1 R ist hier …",
        "vorher festgelegtes Geldrisiko",
        "immer 1 €",
        "immer der Gewinn",
        "Die Definition bleibt über das Journal konsistent.",
      ],
      [
        "Zehn gute Versuche sind …",
        "eine kleine unsichere Stichprobe",
        "sicherer Vorteil",
        "eine Garantie",
        "Zufällige Schwankungen sind bei kleinen Stichproben groß.",
      ],
      [
        "0,5×80 − 0,5×40 − 4?",
        "16 €",
        "20 €",
        "36 €",
        "40−20−4 = 16 € netto im Modell.",
      ],
    ],
  ),
  L(
    13,
    "Ruhig & nachvollziehbar handeln",
    "Dein Lernprozess",
    "Gute Entscheidungen lassen sich erklären.",
    ["FOMO und Revenge Trading erkennen", "Ehrliches Backtesting planen"],
    [
      [
        "Gefühle benennen",
        "FOMO ist die Angst, eine Gelegenheit zu verpassen. Revenge Trading ist impulsives Handeln, um Verluste sofort zurückzuholen. Eine Pause und eine schriftliche Begründung machen den Entscheidungsprozess sichtbar.",
      ],
      [
        "Eigene Prozessregeln",
        "Kläre Produkt, Kosten und Risiko vorher. Erhöhe Risiko nicht impulsiv. Eine selbst gewählte Tagesverlustgrenze ist eine Übungsregel, kein Marktgesetz. Auch Nicht-Handeln kann eine bewusste Entscheidung sein.",
      ],
      [
        "Backtesting ohne Selbsttäuschung",
        "Backtesting prüft feste Regeln an historischen Daten. Look-ahead-Bias verwendet damals unbekannte Zukunftsdaten. Nur Gewinner auszuwählen, Kosten wegzulassen oder Regeln nach Verlusten anzupassen verzerrt Ergebnisse. Regeln vorher festlegen, alle Fälle erfassen und an ungenutzten Daten gegenprüfen.",
      ],
    ],
    "Nach zwei Verlusten spontan die Menge verdoppeln bleibt ein Regelverstoß, auch wenn der nächste Versuch gewinnt.",
    "20 Gewinner à 10 €, 10 Verluste à 15 €, Kosten 1 € je Versuch: Gesamtnetto?",
    "20 € = 200−150−30.",
    "Gewinn stärker belohnen als saubere Entscheidungen; Fälle nach Ergebnis auswählen.",
    "Das Ergebnis rechtfertigt keinen Regelverstoß. Dokumentiere ehrlich.",
    "Erstellt einen Testplan mit Regeln, Kosten, Zeitraum und unabhängigen Prüfdaten.",
    [
      [
        "FOMO bedeutet …",
        "Angst, etwas zu verpassen",
        "Ordermechanismus",
        "risikofreier Gewinn",
        "Emotionale Dringlichkeit ersetzt keinen Plan.",
      ],
      [
        "Revenge Trading ist …",
        "impulsives Zurückholen von Verlusten",
        "geplante Wiederholung",
        "Börsenregel",
        "Der Wunsch nach Ausgleich verdrängt den Plan.",
      ],
      [
        "Ein gewinnender Regelverstoß …",
        "bleibt Regelverstoß",
        "ist automatisch korrekt",
        "muss wiederholt werden",
        "Prozess und Ergebnis werden getrennt bewertet.",
      ],
      [
        "Look-ahead-Bias heißt …",
        "Zukunftsdaten verwenden",
        "Kosten erfassen",
        "alle Fälle prüfen",
        "Die Information war zum Entscheidungszeitpunkt unbekannt.",
      ],
      [
        "Nur Gewinner auswählen …",
        "verzerrt die Auswertung",
        "ist vollständig",
        "garantiert Qualität",
        "Verluste werden ausgeblendet.",
      ],
      [
        "Regeln festlegen …",
        "vor dem Test",
        "nach jedem Verlust",
        "nie schriftlich",
        "Nachträgliches Anpassen kann Überanpassung erzeugen.",
      ],
      [
        "Tagesverlustgrenze ist …",
        "persönliche Übungsgrenze",
        "universeller Prozentsatz",
        "Börsenkurs",
        "Sie ist frei gewählt und garantiert keine Ausführungssumme.",
      ],
      [
        "20×10 − 10×15 − 30×1?",
        "20 €",
        "50 €",
        "200 €",
        "Alle Versuche und Kosten zählen: 200−150−30.",
      ],
    ],
  ),
  L(
    14,
    "Bereit für das Strategiegespräch",
    "Dein Lernprozess",
    "Grundlagen verbinden. Gute Fragen mitbringen.",
    ["Wissen und Praxis nachweisen", "Offene Fragen formulieren"],
    [
      [
        "Dein Abschluss",
        "Bearbeite 30 Fragen und die Praxisprüfung: Kerzen, Struktur, Bereiche, Orders, Hebel und Rechnen. Ab 80 % ist der Wissenstest bestanden. Kritische Aufgaben müssen zusätzlich jeweils korrekt gelöst sein; eine gute Gesamtnote ersetzt das nicht.",
      ],
      [
        "Fragen an euren Freund",
        "Welches genaue Instrument? Welcher Punktwert? Welche Daten und Zeitrahmen? Wie sind Einstieg, Ausstieg und ungültige Bedingungen definiert? Welche Kosten und Slippage? Wie wurde ohne Zukunftswissen getestet? Welche Stichprobe und Verlustserien gab es?",
      ],
      [
        "Grenzen des Nachweises",
        "Der Abschluss ist ein Lernnachweis für geprüfte Grundlagen. Er ist keine Freigabe und kein Nachweis für profitables Echtgeldtrading. Wiederholt offene Themen in eurem Tempo; ein Datum erzwingt keine Beherrschung.",
      ],
    ],
    "Eine konkrete Frage lautet: Welchen Geldwert je Preiseinheit hat genau dieser Kontrakt und wo steht das?",
    "24/30 richtig, aber Hebelpraxis falsch: vollständiger Nachweis?",
    "Nein. Wissen mit 80 % bestanden, kritische Praxis fehlt.",
    "Kalender mit Kompetenz verwechseln; Regeln blind übernehmen.",
    "Verstehen heißt erklären, rechnen und Grenzen benennen.",
    "Führt ein Probe-Gespräch und sucht fehlende Spezifikationen in einem erfundenen Regelwerk.",
    [
      [
        "24 von 30 sind …",
        "80 %",
        "75 %",
        "90 %",
        "24 geteilt durch 30 = 0,8, also 80 % richtig beantwortet.",
      ],
      [
        "Wissen bestanden, Hebelpraxis falsch: Abschluss?",
        "Noch nicht vollständig",
        "Automatisch vollständig",
        "Durch Gewinn ersetzt",
        "Kritische Praxis muss separat bestanden sein.",
      ],
      [
        "Erste Produktfrage?",
        "Welcher genaue Kontrakt?",
        "Wie schnell reich?",
        "Welche Chartfarbe?",
        "Ohne Kontrakt fehlen Einheiten und Bedingungen.",
      ],
      [
        "Ein ehrlicher Test berücksichtigt …",
        "Kosten und Slippage",
        "nur Wunschkurse",
        "nur Gewinner",
        "Reibung beeinflusst Ausführungen und Ergebnisse.",
      ],
      [
        "Lernnachweis bedeutet …",
        "geprüfte Grundlagen",
        "Echtgeldfreigabe",
        "Profitabilitätsbeweis",
        "Die Aussage ist auf die Lernaufgaben begrenzt.",
      ],
      [
        "Unklare Regeln …",
        "vor dem Test präzisieren",
        "nach Ergebnis auslegen",
        "ignorieren",
        "Nur klare Regeln sind prüfbar.",
      ],
      [
        "Nach 14 Tagen noch Fragen?",
        "Weiterlernen und wiederholen",
        "Echtgeld starten",
        "Fortschritt löschen",
        "Tempo ist individuell.",
      ],
      [
        "Welche Frage prüft Zukunftswissen?",
        "Welche Daten waren damals sichtbar?",
        "Wie schön ist die Kurve?",
        "Wie hoch nur der beste Gewinn?",
        "Zeitlich verfügbare Information ist entscheidend.",
      ],
    ],
  ),
];
export const questions = lessons.flatMap((l) => l.quiz);
export const sources = [
  {
    title: "SEC / Investor.gov · Ordertypen und Ausführungsrisiken",
    url: "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-14",
    note: "US-Aktien; konkrete Anbieterbedingungen können abweichen.",
  },
  {
    title: "CME Group · Margin: Know What's Needed",
    url: "https://www.cmegroup.com/education/courses/introduction-to-futures/margin-know-what-is-needed",
    note: "Futures: Sicherheitsleistungen, keine Verlustobergrenzen.",
  },
  {
    title: "CME Group · A Trader’s Guide to Futures",
    url: "https://www.cmegroup.com/education/files/a-traders-guide-to-futures.pdf",
    note: "Kontrakte, Tickwerte und produktspezifische Risiken.",
  },
  {
    title: "ESMA · Warnung zu CFDs und spekulativen Produkten",
    url: "https://www.esma.europa.eu/document/warning-about-cfds-binary-options-and-other-speculative-products",
    note: "Europäische Risikoeinordnung, keine universellen Rechtsregeln.",
  },
];
export const glossary: [string, string, string][] = [
  [
    "Trading",
    "Handeln auf Preisänderungen.",
    "Simulierter Kauf 100, Verkauf 102.",
  ],
  [
    "Position",
    "Gehaltene Menge eines Instruments.",
    "Zwei Einheiten eines fiktiven Kontrakts.",
  ],
  [
    "Aktie",
    "Anteil an einem Unternehmen.",
    "Der Inhaber ist anteiliger Eigentümer.",
  ],
  [
    "Index",
    "Berechnete Messgröße eines Marktkorbs.",
    "Dow Jones allein ist kein Kontrakt.",
  ],
  ["ETF", "Börsengehandelter Fonds.", "Ein ETF kann einen Index nachbilden."],
  [
    "CFD",
    "Differenzvertrag mit einem Anbieter.",
    "Punktwert und Kosten sind produktspezifisch.",
  ],
  [
    "Future",
    "Standardisierter Terminkontrakt.",
    "Fälligkeit und Tickgröße sind festgelegt.",
  ],
  [
    "Tick",
    "Kleinste zulässige Preisänderung.",
    "0,25 Punkte × 4 €/Punkt = 1 € je Tick und Einheit.",
  ],
  [
    "Punktwert",
    "Geldwert einer Preiseinheit je Einheit der Position.",
    "2 €/Punkt × 3 Punkte × 2 Einheiten = 12 €.",
  ],
  ["OHLC", "Eröffnung, Hoch, Tief und Schluss.", "O100, H105, L98, C103."],
  [
    "Docht",
    "Kerzenteil zwischen Körper und Extrempreis.",
    "Körper endet 103, Hoch 105: oberer Docht 2 Punkte.",
  ],
  [
    "Zeitrahmen",
    "Dauer eines Chartintervalls.",
    "Fünf vollständige 1-Minuten-Kerzen ergeben eine 5-Minuten-Kerze.",
  ],
  [
    "Swing",
    "Lokaler Hoch- oder Tiefpunkt nach einer festen Regel.",
    "Hier strikt höher/tiefer als je zwei geschlossene Nachbarkerzen.",
  ],
  [
    "Unterstützung",
    "Bereich früherer Reaktionen nach Rückgängen.",
    "Tiefs um 100 können 99–101 begründen.",
  ],
  [
    "Widerstand",
    "Bereich früherer Reaktionen nach Anstiegen.",
    "Hochs um 112 ergeben keinen sicheren Deckel.",
  ],
  [
    "Bid",
    "Preis der Käuferseite, typisch zum Verkaufen.",
    "Bid 100 bei Ask 100,4.",
  ],
  [
    "Ask",
    "Preis der Verkäuferseite, typisch zum Kaufen.",
    "Ask 100,4 bei Bid 100.",
  ],
  ["Spread", "Ask minus Bid.", "100,4−100 = 0,4 Punkte."],
  [
    "Liquidität",
    "Handelbarkeit von Mengen ohne starke Preiswirkung.",
    "Wenige Gegenorders können Slippage vergrößern.",
  ],
  [
    "Volumen",
    "Gehandelte Menge; Bedeutung hängt von der Quelle ab.",
    "Tickvolumen zählt Preisaktualisierungen.",
  ],
  [
    "Volatilität",
    "Stärke von Preisschwankungen.",
    "Große Spannen bedeuten stärkere Schwankungen.",
  ],
  [
    "Slippage",
    "Abweichung vom erwarteten Ausführungspreis.",
    "Kauf erwartet 100, tatsächlich 100,5.",
  ],
  [
    "Long",
    "Profitiert vor Kosten von steigenden Preisen.",
    "100 kaufen, 103 verkaufen: +3 Punkte.",
  ],
  [
    "Short",
    "Profitiert vor Kosten von fallenden Preisen.",
    "100 verkaufen, 97 zurückkaufen: +3 Punkte.",
  ],
  ["Market", "Auftrag zum verfügbaren Preis.", "Keine feste Preisgarantie."],
  [
    "Limit",
    "Preisgrenze für einen Auftrag.",
    "Kauf maximal 98; Ausführung kann ausbleiben.",
  ],
  [
    "Stop-Limit",
    "Wird nach Auslösung zum Limit-Auftrag.",
    "Stop 95/Limit 94 kann bei Sprung auf 92 ungefüllt bleiben.",
  ],
  [
    "Stop-Loss",
    "Geplanter Verlustausstieg.",
    "Stop 95 garantiert keinen Ausstieg genau bei 95.",
  ],
  [
    "Take-Profit",
    "Geplanter Gewinnausstieg.",
    "Verkaufslimit 110 bei Einstieg 100.",
  ],
  [
    "Hebel",
    "Positionswert geteilt durch betrachtetes Eigenkapital.",
    "5.000/1.000 = 5:1.",
  ],
  [
    "Margin",
    "Sicherheitsleistung, kein maximaler Verlust.",
    "Die Sicherheit kann kleiner als der Positionswert sein.",
  ],
  [
    "Drawdown",
    "Rückgang vom bisherigen Kapitalhoch.",
    "1.000 auf 800 € = 20 %.",
  ],
  [
    "CRV",
    "Geplanter Gewinn geteilt durch geplanten Verlust.",
    "100/50 = 2:1 vor Kosten.",
  ],
  [
    "R",
    "Vorher festgelegtes Geldrisiko als Ergebniseinheit.",
    "1 R = 50 €; 75 € netto = 1,5 R.",
  ],
  [
    "Erwartungswert",
    "Rechnerisches Durchschnittsergebnis im Modell.",
    "0,4×100−0,6×50−5 = 5 € netto.",
  ],
  [
    "FOMO",
    "Angst, etwas zu verpassen.",
    "Einer Bewegung ohne Plan hinterherlaufen.",
  ],
  [
    "Revenge Trading",
    "Impulsives Zurückholen von Verlusten.",
    "Spontanes Verdoppeln nach Verlust.",
  ],
  [
    "Backtesting",
    "Prüfung fester Regeln an historischen Daten.",
    "Alle Fälle und Kosten erfassen, ungenutzte Daten gegenprüfen.",
  ],
  [
    "Look-ahead-Bias",
    "Verwendung damals unbekannter Zukunftsdaten.",
    "Swing handeln, bevor rechte Kerzen geschlossen sind.",
  ],
];
