"use client";

import { type FormEvent, useEffect, useRef, useState } from "react";
import type { Socket } from "socket.io-client";
import { SettingsButton } from "@/components/SettingsDialog";
import { useI18n, useLocalizedError } from "@/i18n/I18nProvider";
import type { ChatMessage, Room } from "@/types/room";

type Props = { cameraStream: MediaStream | null; chatMessages: ChatMessage[]; currentPlayerId: string; error?: string; micStream: MediaStream | null; onCameraStreamChange: (stream: MediaStream | null) => void; onMicStreamChange: (stream: MediaStream | null) => void; onSendChat: (message: string) => void; onStartGame: () => void; onLeaveRoom: () => void; room: Room; socket: Socket | null };

export function RoomPanel({ cameraStream, chatMessages, currentPlayerId, error, micStream, onCameraStreamChange, onMicStreamChange, onSendChat, onStartGame, onLeaveRoom, room, socket }: Props) {
  const { language, t } = useI18n();
  const localizedError = useLocalizedError(error);
  const [chatDraft, setChatDraft] = useState("");
  const [copyState, setCopyState] = useState<"idle" | "copied" | "failed">("idle");
  const [mediaError, setMediaError] = useState("");
  const chatRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const followChatRef = useRef(true);
  const isHost = room.hostId === currentPlayerId;

  useEffect(() => { if (videoRef.current) videoRef.current.srcObject = cameraStream; }, [cameraStream]);
  useEffect(() => { socket?.emit("media:status", { cameraOn: Boolean(cameraStream), micOn: Boolean(micStream) }); }, [cameraStream, micStream, socket]);
  useEffect(() => { if (followChatRef.current && chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight; }, [chatMessages]);

  async function copyCode() { try { await navigator.clipboard.writeText(room.code); setCopyState("copied"); } catch { setCopyState("failed"); } window.setTimeout(() => setCopyState("idle"), 2500); }
  async function toggleCamera() { setMediaError(""); if (cameraStream) { cameraStream.getTracks().forEach((track) => track.stop()); onCameraStreamChange(null); return; } try { onCameraStreamChange(await navigator.mediaDevices.getUserMedia({ video: true, audio: false })); } catch { setMediaError(t("cameraBlocked")); } }
  async function toggleMic() { setMediaError(""); if (micStream) { micStream.getTracks().forEach((track) => track.stop()); onMicStreamChange(null); return; } try { onMicStreamChange(await navigator.mediaDevices.getUserMedia({ video: false, audio: true })); } catch { setMediaError(t("micBlocked")); } }
  function sendChat(event: FormEvent) { event.preventDefault(); const message = chatDraft.trim(); if (!message) return; onSendChat(message); setChatDraft(""); followChatRef.current = true; }

  return <main className="min-h-screen overflow-x-hidden bg-black px-3 py-4 text-white sm:px-6 sm:py-6"><div className="mx-auto max-w-[1440px] rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_top,rgba(212,175,55,.09),transparent_35%),#080808] p-4 shadow-2xl sm:p-6">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-5"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[.28em] text-[#d4af37]">{t("waitingRoom")}</p><h1 className="text-4xl font-black">RAVO</h1></div><div className="flex flex-wrap items-center justify-end gap-2"><strong className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 tracking-[.16em]">{room.code}</strong><button type="button" onClick={copyCode} className="rounded-xl border border-[#d4af37]/40 px-4 py-2 text-sm font-bold text-[#f7d86d]">{copyState === "copied" ? t("copied") : t("copyCode")}</button><SettingsButton className="grid h-10 w-10 place-items-center rounded-xl border border-white/15"/><button type="button" onClick={() => { if (window.confirm(t("leaveConfirm"))) onLeaveRoom(); }} className="rounded-xl border border-white/15 px-4 py-2 text-sm font-bold text-zinc-300">{t("leaveRoom")}</button></div>{copyState === "failed" ? <p role="alert" className="w-full text-right text-sm text-red-300">{t("copyFailed")}</p> : null}</header>
    <div className="mt-6 grid min-w-0 gap-6 lg:grid-cols-[minmax(280px,.8fr)_minmax(0,1.2fr)]">
      <section className="min-w-0 rounded-3xl border border-white/10 bg-black/55 p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{t("players")}</h2><span className="rounded-full bg-white/5 px-3 py-1 text-sm font-bold">{room.players.length}/8</span></div><div className="mt-4 max-h-[410px] space-y-2 overflow-y-auto pr-1">{room.players.map((player) => <div key={player.id} className="flex min-w-0 items-center gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#d4af37]/15 font-black text-[#f7d86d]">{player.name.trim().slice(0,2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate font-bold" title={player.name}>{player.name}</p><p className="text-xs text-zinc-500">{player.id === room.hostId ? t("host") : t("player")}{player.id === currentPlayerId ? ` · ${t("you")}` : ""}</p></div></div>)}</div>
        {localizedError ? <p role="alert" className="mt-4 rounded-xl border border-red-500/30 bg-red-950/30 p-3 text-sm text-red-200">{localizedError}</p> : null}{isHost ? <><button type="button" disabled={room.players.length < 2} onClick={onStartGame} className="mt-5 h-12 w-full rounded-xl bg-white font-black text-black disabled:cursor-not-allowed disabled:opacity-40">{t("startGame")}</button>{room.players.length < 2 ? <p className="mt-2 text-center text-xs text-zinc-500">{t("needPlayers")}</p> : null}</> : <p className="mt-5 rounded-xl bg-white/5 p-4 text-center text-sm text-zinc-400">{t("waitingHost")}</p>}
        <details className="mt-5 rounded-2xl border border-white/10 bg-white/[.025] p-4"><summary className="cursor-pointer font-bold">{t("media")}</summary><p className="mt-2 text-xs text-zinc-500">{t("mediaHint")}</p>{cameraStream ? <video ref={videoRef} autoPlay muted playsInline className="mt-3 aspect-video w-full rounded-xl object-cover"/> : null}<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={toggleCamera} className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-bold">{t("camera")}: {t(cameraStream ? "on" : "off")}</button><button type="button" onClick={toggleMic} className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-bold">{t("microphone")}: {t(micStream ? "on" : "off")}</button></div>{mediaError ? <p role="alert" className="mt-3 text-sm text-red-300">{mediaError}</p> : null}</details>
      </section>
      <section className="grid min-h-[480px] min-w-0 grid-rows-[auto_1fr_auto] rounded-3xl border border-white/10 bg-black/55 p-5"><h2 className="text-xl font-black">{t("lobbyChat")}</h2><div ref={chatRef} onScroll={(event) => { const element=event.currentTarget; followChatRef.current=element.scrollHeight-element.scrollTop-element.clientHeight<48; }} className="mt-4 min-h-0 overflow-y-auto rounded-2xl border border-white/10 bg-black/45 p-3">{chatMessages.length ? <div className="space-y-3">{chatMessages.map((message) => <article key={message.id} className="min-w-0 rounded-xl bg-white/[.05] p-3"><div className="flex gap-3"><strong className="min-w-0 flex-1 truncate">{message.playerName}</strong><time className="text-xs text-zinc-600">{new Intl.DateTimeFormat(language,{hour:"2-digit",minute:"2-digit"}).format(message.sentAt)}</time></div><p className="mt-1 break-words [overflow-wrap:anywhere] text-sm text-zinc-300">{message.message}</p></article>)}</div> : <div className="grid h-full place-items-center text-sm text-zinc-600">{t("noMessages")}</div>}</div><form onSubmit={sendChat} className="mt-3 flex min-w-0 gap-2"><input value={chatDraft} onChange={(e)=>setChatDraft(e.target.value)} placeholder={t("typeMessage")} className="h-12 min-w-0 flex-1 rounded-xl border border-white/10 bg-black px-4 outline-none focus:border-[#d4af37]/60"/><button type="submit" disabled={!chatDraft.trim()} className="rounded-xl border border-[#d4af37]/40 px-5 font-bold text-[#f7d86d] disabled:opacity-40">{t("send")}</button></form></section>
    </div>
  </div></main>;
}
